import { Focus, Genre, Tag } from '@prisma/client';
// prettier-ignore
export const genresMap : Record<string,Tag | Genre | Focus> = {
  "au": Tag.AU,
  "ангст": Tag.ANGST,
  'нецензурная лексика': Tag.NSFW,
  'hurt/comfort': Tag.HURT_COMFORT,
  "психология": Tag.PSYCHOLOGY,
  'смерть основных персонажей': Tag.CHARACTER_DEATH,
  "дружба": Tag.FRIENDSHIP,
  "насилие": Tag.VIOLENCE,
  "фэнтези": Tag.FANTASY,
  'веб-комикс': Focus.WEB_COMIC,
  "манга": Focus.MANGA,
  "сингл": Focus.SINGLE,
  "мини": Focus.MINI,
  "макси": Focus.MAXI,
  'омнибус (сборник)': Focus.OMNIBUS,
  "комедия": Genre.COMEDY,
  "боевик": Genre.ACTION,
  "драма": Genre.DRAMA,
  "детектив": Genre.DETECTIVE,
  "триллер": Genre.THRILLER,
  "романтика": Genre.ROMANCE,
  "мелодрама": Genre.MELODRAMA,
  "повседневность": Genre.DAILY_LIFE,
  "спорт": Genre.SPORT,
  "хоррор": Genre.HORROR,
  'фантастика': Genre.SCI_FI,
  'историческая драма': Genre.HISTORICAL_DRAMA,
  "гарем": Genre.HAREM,
  "киберпанк": Genre.CYBERPUNK,
  "стимпанк": Genre.STEAMPUNK,
  "супергерои": Genre.SUPERHERO,
  'космическая опера': Genre.SPACE_OPERA,
  "апокалипсис": Genre.APOCALYPSE,
  "постапокалипсис": Genre.POST_APOCALYPSE,
  'боевые искусства': Genre.MARTIAL_ARTS,
  "айдолы": Genre.IDOLS,
  "меха": Genre.MECHA,
  "фансервис": Genre.FAN_SERVICE,
  "этти": Genre.ECHI,
};

export const reverseMap: Record<string, string> = Object.fromEntries(
  Object.entries(genresMap).map((items) => items.reverse()),
);
