import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import ContextProvider from '@/context/contextProvider';
import Layout from '@/components/layout';
import ScrollToTop from '@/components/ScrollToTop';
import '../styles/style.scss'
const montserrat = Montserrat({ subsets: ['latin'],weight:['400','500','600','700']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={montserrat.className}>{

        <ContextProvider>
          <Layout>
            {children}
          <ScrollToTop/>
          </Layout>
           
        </ContextProvider>

      }</body>
    </html>
  );
};

export default RootLayout;


